version: '3'
services:
  nginx:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/jacob-project/nginx:latest
    restart: always
    env_file:
      - ./nginx.env
    command: "sh /start.sh"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend:/frontend
      - pdfs:/pdfs
      - htmls:/htmls
      - media-files:/media-files
      - static-files:/static-files
      - ./config:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  frontend:
    external: true
  pdfs:
    external: true
  htmls:
    external: true
  media-files:
    external: true
  static-files:
    external: true

networks:
  default:
    external:
      name: jacob
